### PR TITLE
Create Articulation_point1GFG.java

### PR DESCRIPTION
**Pull request by Karan-Hora**

### CODE REVIEW

**Review by Sagar0-0 — CHANGES_REQUESTED** [review]
Please add the extension ".java"

**Comment by Karan-Hora** [comment]
bro i am new in this so can tell in brief where i have to add the extension

**Comment by Karan-Hora** [comment]
done bro added the extension

**Comment by Sagar0-0** [comment]
No changes are there, I am closing this PR, you can modify your file and create new PR. Thanks for contributing.

**Pull request closed without merging**
