### PR TITLE
75. Sort Colors

### PR DESCRIPTION
**Pull request by Shivamchauhan29**
**Please fill the deatils before contributing.**

# ⚠️Important!!
- [x] Done reading [CONTRIBUTING.md](https://github.com/Sagar0-0/DsA/blob/main/CONTRIBUTING.md)?

# Adding Code PRs?🔥
⚠️Do not add multiple files for the same solution!!!
- [x] Added problem statement(Readme.md) with solution?

- [x] Contributing new file?
- [x] Appending your code in already existing file?

### From Platform:

- [x] Leetcode 
- [ ] GFG 
- [ ] Interviewbit
- [ ] Others(only acceptable after DISCUSSIONS)

[Link to the problem]()

# Migration PRs?🤝

- [x] Done deleteing file from home directory?
- [x] Added file with correct name and correct directory?

### CODE REVIEW

**Comment by Shivamchauhan29** [comment]
Completed the tasks

**Review by Sagar0-0 — CHANGES_REQUESTED** [review]
Leetcode questions should be in Leetcode folder, make changes in your PR only after reading contriuting.md or I have to mark your PR as invalid

**Comment by Shivamchauhan29** [comment]
Changed the directory to the leetcode .

**Comment by Shivamchauhan29** [comment]
can you please tell me what is the issue now. I am a new contributer so not familiar too much with the same . 
Please tell me if there is any issue .

**Review by Sagar0-0 — APPROVED** [review]

**Comment by Sagar0-0** [comment]
LGTM

**Pull request merged**
