### PR TITLE
Moved 2 code from home directory to correct folder for better structuring of the repository

### PR DESCRIPTION
**Pull request by HarshKrishan**
**Please fill the deatils before contributing.**

# ⚠️Important!!
- [x] Done reading [CONTRIBUTING.md](https://github.com/Sagar0-0/DsA/blob/main/CONTRIBUTING.md)?

# Adding Code PRs?🔥
⚠️Do not add multiple files for the same solution!!!
- [ ] Added problem statement(Readme.md) with solution?

- [ ] Contributing new file?
- [ ] Appending your code in already existing file?

### From Platform:

- [ ] Leetcode 
- [ ] GFG 
- [ ] Interviewbit
- [ ] Others(only acceptable after DISCUSSIONS)

[Link to the problem]()

# Migration PRs?🤝

- [x] Done deleteing file from home directory?
- [x] Added file with correct name and correct directory?

### CODE REVIEW

**Comment by HarshKrishan** [comment]
Kindly inform me once, if I have done it right. I would love to contribute to this repository in the future as much as possible. @Sagar0-0

**Review by Sagar0-0 — APPROVED** [review]

**Comment by HarshKrishan** [comment]
Thanks for merging my pull request. 

Here's a suggestion from me-->

Should I start adding the names with their profile links (commented) of the original contributors as well (in the moved code)?

Although I don't remember the names of the previous two contributors I moved, I will take care of this next time. If you allow me to do so.

**Comment by Sagar0-0** [comment]
No problem, you are doing a great job!

**Comment by HarshKrishan** [comment]
Thanks for your appreciation :)

**Pull request merged**
