### PR TITLE
Added the Soln. of Prblm 2428 LeetCode

### PR DESCRIPTION
**Pull request by ratnakeraditya04**
**Please fill the details before contributing.**

# ⚠️Important!!

- [x] Done reading [CONTRIBUTING.md](https://github.com/Sagar0-0/DsA/blob/main/CONTRIBUTING.md)?

# Adding Code PRs?🔥
⚠️Do not add multiple files for the same solution!!!
- [ ] Added problem statement(Readme.md) with solution?

- [x] Contributing new file?
- [ ] Appending your code in already existing file?

### From Platform:

- [x] Leetcode 
- [ ] GFG 
- [ ] Interviewbit
- [ ] Others(only acceptable after DISCUSSIONS)

# Migration PRs?🤝

- [ ] Done deleteing file from home directory?
- [ ] Added file with correct name and correct directory?

### CODE REVIEW

**Comment by ratnakeraditya04** [comment]
I am new to contributing to Open Source Projects. So with all due respect to maintainers of this repository, if any error occur or I am unable to follow any of the contributing guidelines of DsA repository which I am unaware of or I happen to miss it to follow, kindly do not mark this merge request as spam PR. 
This Question which I am contributing is part of LeetCode Weekly Contest - 313 which happened on 02_10_2022. I solved the problem in C++ Programming Language.

**Review by Sagar0-0 — APPROVED** [review]
Please add the exact same name of the question in the file name or check if same solution file already exists, then you can append your code there. Read contributing.md file carefully to better understand the structure.

**Review by Sagar0-0 — CHANGES_REQUESTED** [review]
Add the correct name.

**Comment by ratnakeraditya04** [comment]
I am not able to update the name. I will try again.

**Pull request closed without merging**
