### PR TITLE
ervaibhavkumar Adding code for Binary Search in Python

### PR DESCRIPTION
**Pull request by ervaibhavkumar**
**Please fill the deatils before contributing.**

# ⚠️Important!!
- [x] Done reading [CONTRIBUTING.md](https://github.com/Sagar0-0/DsA/blob/main/CONTRIBUTING.md)?

# Adding Code PRs?🔥
⚠️Do not add multiple files for the same solution!!!
- [ ] Added problem statement(Readme.md) with solution?

- [x] Contributing new file?
- [ ] Appending your code in already existing file?

### From Platform:

- [x] Leetcode 
- [ ] GFG 
- [ ] Interviewbit
- [ ] Others(only acceptable after DISCUSSIONS)

[Link to the problem]()

[Binary Search](https://leetcode.com/problems/binary-search/)

# Migration PRs?🤝

- [ ] Done deleteing file from home directory?
- [ ] Added file with correct name and correct directory?

### CODE REVIEW

**Review by Sagar0-0 — CHANGES_REQUESTED** [review]
Please read contributing.md file carefully before creating any PR and make changes in your PR accordingly. Add these files and folder in the Leetcode directory.

**Comment by ervaibhavkumar** [comment]
Thanks for the comment. I'll make the changes

**Comment by ervaibhavkumar** [comment]
@Sagar0-0 Thanks for the comments. I have integrated the suggested changes. Please let me know if I missed something. Happy to fix. Thanks :)

**Review by Sagar0-0 — CHANGES_REQUESTED** [review]
Please do not use "-"(hyphen) in the name of your file.

**Review by Sagar0-0 — APPROVED** [review]

**Comment by ervaibhavkumar** [comment]
@Sagar0-0 Thanks for pointing out. I have updated the file and folder name.

**Comment by ervaibhavkumar** [comment]
@Sagar0-0 Thanks for merging the PR. It would be great if you can you also add the hacktoberfest-accepted label. Thanks :)

**Pull request merged**
