### PR TITLE
 Queries on a matrix gfg

### PR DESCRIPTION
**Pull request by AnishMandal939**

### CODE REVIEW

**Comment by Sagar0-0** [comment]
Please read the new [Contributing.md](https://github.com/Sagar0-0/DsA/blob/main/CONTRIBUTING.md) and make changes in your PR accordingly. Thank you

**Comment by AnishMandal939** [comment]
placed in respective folders

**Review by Sagar0-0 — CHANGES_REQUESTED** [review]
Respectice folders for platforms are already created with the names "Leetcode" and "GFG" please check them out and append only in them

**Comment by AnishMandal939** [comment]
changed directories and pushed to directories that you suggested please do have a check

**Review by Sagar0-0 — CHANGES_REQUESTED** [review]
All the files are added to the right directory, but still there are unwanted files present in the home directory and also duplicate leetcode/geeks for geeks folder, please clean up and delete all unwanted stuff.

**Comment by AnishMandal939** [comment]
@Sagar0-0 hope this it's all okey deleted files from main directory and all are structured respectively

**Review by AnishMandal939 — COMMENTED** [review]
deleted all files that were outside of path

**Review by Sagar0-0 — APPROVED** [review]
Thanks for your time and efforts.

**Pull request merged**
