### PR TITLE
valid_parenthesis.java

### PR DESCRIPTION
**Pull request by Faisalansari203**

### CODE REVIEW

**Review by Sagar0-0 — APPROVED** [review]
Thanks feju bhaiya

**Comment by Faisalansari203** [comment]
Kya mtlb merged int main   Sent from Mail for Windows From: SagarSent: Saturday, September 24, 2022 3:37 PMTo: Sagar0-0/DsACc: Faisalansari203; AuthorSubject: Re: [Sagar0-0/DsA] valid_parenthesis.java (PR #347) Merged #347 into main.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Faisalansari203** [comment]
Always bitch More on the way stay tuned  Sent from Mail for Windows From: SagarSent: Saturday, September 24, 2022 3:36 PMTo: Sagar0-0/DsACc: Faisalansari203; AuthorSubject: Re: [Sagar0-0/DsA] valid_parenthesis.java (PR ***@***.*** approved this pull request.Thanks feju bhaiya—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Sagar0-0** [comment]
Kya bakchodi krra h

**Comment by Faisalansari203** [comment]
Konsi  Sent from Mail for Windows From: SagarSent: Tuesday, October 11, 2022 1:52 PMTo: Sagar0-0/DsACc: Faisalansari203; AuthorSubject: Re: [Sagar0-0/DsA] valid_parenthesis.java (PR #347) Kya bakchodi krra h—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Pull request merged**
