### PR TITLE
1335. Minimum Difficulty of a Job Schedule

### PR DESCRIPTION
**Pull request by worldwinner-vishav**
**Please fill the details before contributing.**

# ⚠️Important!!

- [x] Done reading [CONTRIBUTING.md](https://github.com/Sagar0-0/DsA/blob/main/CONTRIBUTING.md)?

# Adding Code PRs?🔥
⚠️Do not add multiple files for the same solution!!!
- [ ] Added problem statement(Readme.md) with solution?

- [x] Contributing new file?
- [ ] Appending your code in already existing file?

### From Platform:

- [x] Leetcode 
- [ ] GFG 
- [ ] Interviewbit
- [ ] Others(only acceptable after DISCUSSIONS)

# Migration PRs?🤝

- [ ] Done deleteing file from home directory?
- [x] Added file with correct name and correct directory?

### CODE REVIEW

**Review by Sagar0-0 — CHANGES_REQUESTED** [review]
Please check your commits/files changed and see what and how you are contributing the files. Read contributing.md very carefully before creating any PR.

**Comment by worldwinner-vishav** [comment]
File name changed

**Review by Sagar0-0 — CHANGES_REQUESTED** [review]
Please check how many files you are adding to the home directory, which is strictly not acceptable, if you are creating any PR, you must check what things are you adding.

**Comment by Sagar0-0** [comment]
Still you have not resolved the issue, next time I have no other option but to ban you from contributing here.

**Pull request closed without merging**
