### PR TITLE
Leetcode 401 Binary Watch

### PR DESCRIPTION
**Pull request by Jay-Thesia**
**Please fill the deatils before contributing.**

# ⚠️Important!!
- [x] Done reading [CONTRIBUTING.md](https://github.com/Sagar0-0/DsA/blob/main/CONTRIBUTING.md)?

# Adding Code PRs?🔥
⚠️Do not add multiple files for the same solution!!!
- [x] Added problem statement(Readme.md) with solution?

- [x] Contributing new file?
- [ ] Appending your code in already existing file?

### From Platform:

- [x] Leetcode 
- [ ] GFG 
- [ ] Interviewbit
- [ ] Others(only acceptable after DISCUSSIONS)

[Link to the problem](https://leetcode.com/problems/binary-watch/)

# Migration PRs?🤝

- [ ] Done deleteing file from home directory?
- [ ] Added file with correct name and correct directory?

### CODE REVIEW

**Comment by Jay-Thesia** [comment]
Add my Pull request with the tag of **"Hacktoberfest2022"**

**Review by Sagar0-0 — APPROVED** [review]

**Comment by Sagar0-0** [comment]
Check if it is showing as accepted PR and let me know.

**Comment by Jay-Thesia** [comment]
Add the “hacktoberfest-accepted” label with the Pull request

**Comment by Jay-Thesia** [comment]
right side you see the label menu from there add the label bhaiya

**Comment by Jay-Thesia** [comment]
Done Bhaiya HO gaya 👍 Thanks

**Comment by Sagar0-0** [comment]
> right side you see the label menu from there add the label bhaiya

This repo explicitly have the hacktoberfest2022 label, so you do not need to add it every time in your PR.

**Pull request merged**
