### PR TITLE
Structured the repository

### PR DESCRIPTION
**Pull request by HarshKrishan**
**Please fill the details before contributing.**

# ⚠️Important!!

- [x] Done reading [CONTRIBUTING.md](https://github.com/Sagar0-0/DsA/blob/main/CONTRIBUTING.md)?

# Adding Code PRs?🔥
⚠️Do not add multiple files for the same solution!!!
- [ ] Added problem statement(Readme.md) with solution?

- [ ] Contributing new file?
- [ ] Appending your code in already existing file?

### From Platform:

- [ ] Leetcode 
- [x] GFG 
- [ ] Interviewbit
- [ ] Others(only acceptable after DISCUSSIONS)

# Migration PRs?🤝

- [x] Done deleteing file from home directory?
- [x] Added file with correct name and correct directory?

### CODE REVIEW

**Review by Sagar0-0 — APPROVED** [review]

**Comment by Sagar0-0** [comment]
Thanks a lot for your contribution..

**Comment by HarshKrishan** [comment]
It's my Pleasure :)

**Comment by HarshKrishan** [comment]
Can you please also mark it as hacktoberfest accepted if possible?

**Comment by HarshKrishan** [comment]
Why is your repository excluded from hactoberfest?

Did you violate any rules required for it?

**Pull request merged**
