### PR TITLE
976. Largest Perimeter Triangle

### PR DESCRIPTION
**Pull request by worldwinner-vishav**
**Please fill the details before contributing.**

# ⚠️Important!!

- [x] Done reading [CONTRIBUTING.md](https://github.com/Sagar0-0/DsA/blob/main/CONTRIBUTING.md)?

# Adding Code PRs?🔥
⚠️Do not add multiple files for the same solution!!!
- [ ] Added problem statement(Readme.md) with solution?

- [x] Contributing new file?
- [ ] Appending your code in already existing file?

### From Platform:

- [x] Leetcode 
- [ ] GFG 
- [ ] Interviewbit
- [ ] Others(only acceptable after DISCUSSIONS)

# Migration PRs?🤝

- [x] Done deleteing file from home directory?
- [x] Added file with correct name and correct directory?

### CODE REVIEW

**Comment by worldwinner-vishav** [comment]
Maximize the sum of selected numbers from a sorted array to make it empty

**Comment by Sagar0-0** [comment]
Before creating a PR MUST check what you are adding. Read contributing.md and make changes accordingly

**Comment by Sagar0-0** [comment]
Just reply here, what issue are you facing and why you are not following contribution guidelines? Or I have to ban you from contributing as you are creating multiple wrong PRs.

**Comment by worldwinner-vishav** [comment]
Sorry, all your previous mails were in the spam folder so, I missed them.
But I promise from now onwards I make PR properly.

**Comment by Sagar0-0** [comment]
Delete all files that are not up to contributing guidelines.

**Comment by worldwinner-vishav** [comment]
Ok, will do that.

**Pull request closed without merging**
