### PR TITLE
659. Split array into consecutive subsequence

### PR DESCRIPTION
**Pull request by PratikAgrawal02**
**Please fill the details before contributing.**

# ⚠️Important!!

- [x] Done reading [CONTRIBUTING.md](https://github.com/Sagar0-0/DsA/blob/main/CONTRIBUTING.md)?

# Adding Code PRs?🔥
⚠️Do not add multiple files for the same solution!!!
- [x] Added problem statement(Readme.md) with solution?

- [x] Contributing new file?
- [ ] Appending your code in already existing file?

### From Platform:

- [x] Leetcode 
- [ ] GFG 
- [ ] Interviewbit
- [ ] Others(only acceptable after DISCUSSIONS)

# Migration PRs?🤝

- [ ] Done deleteing file from home directory?
- [ ] Added file with correct name and correct directory?

### CODE REVIEW

**Comment by PratikAgrawal02** [comment]
Changes Done As requested for file naming

**Review by Sagar0-0 — CHANGES_REQUESTED** [review]
Please read contributing.md before creating any PR. Change the incorrect name.

**Comment by Sagar0-0** [comment]
Incorrect file name.

**Comment by PratikAgrawal02** [comment]
It is correct sir ... I know i am disturbing but can you please correct me

**Pull request closed without merging**
