### PR TITLE
Added GFG Help Ishaan POTD Solution File in JAVA

### PR DESCRIPTION
**Pull request by raj23689**
**Please fill the details before contributing.**

# ⚠️Important!!

- [X] Done reading [CONTRIBUTING.md](https://github.com/Sagar0-0/DsA/blob/main/CONTRIBUTING.md)?

# Adding Code PRs?🔥
⚠️Do not add multiple files for the same solution!!!
- [X] Added problem statement(Readme.md) with solution?

- [X] Contributing new file?
- [ ] Appending your code in already existing file?

### From Platform:

- [ ] Leetcode 
- [X] GFG 
- [ ] Interviewbit
- [ ] Others(only acceptable after DISCUSSIONS)

# Migration PRs?🤝

- [ ] Done deleteing file from home directory?
- [ ] Added file with correct name and correct directory?

### CODE REVIEW

**Comment by raj23689** [comment]
Please add `Hacktoberfest-accepted` label after merging

**Review by Sagar0-0 — CHANGES_REQUESTED** [review]
Follow the given naming formats for both folder and file names.

**Comment by raj23689** [comment]
> Follow the given naming formats for both folder and file names.

Done

**Review by Sagar0-0 — APPROVED** [review]

**Review by Sagar0-0 — CHANGES_REQUESTED** [review]
This file already exists, so append your code there.

**Pull request closed without merging**
